export const tours = [
    { id: 1, name: "Phi Phi Islands Tour", price: "$1400", discount: "30%", image: "/images/tour1.jpg", category: "Tours", rating: 4.3, reviews: 20, location: "Rassada Pier" },
    { id: 2, name: "James Bond Island Tour", price: "$1200", discount: "20%", image: "/images/tour2.jpg", category: "Tours", rating: 4.7, reviews: 15, location: "Phuket Bay" },
    { id: 3, name: "Santorini Sunset Cruise", price: "€180", discount: "15%", image: "/images/tour3.jpg", category: "Tours", rating: 4.5, reviews: 25, location: "Santorini Harbor" },
    { id: 4, name: "Safari Adventure - Kenya", price: "$600", discount: "25%", image: "/images/tour4.jpg", category: "Tours", rating: 4.9, reviews: 32, location: "Nairobi National Park" },
    { id: 5, name: "Northern Lights - Norway", price: "$500", discount: "20%", image: "/images/tour5.jpg", category: "Tours", rating: 4.8, reviews: 27, location: "Tromsø" },
    { id: 6, name: "Machu Picchu Explorer", price: "$250", discount: "10%", image: "/images/tour6.jpg", category: "Tours", rating: 4.6, reviews: 18, location: "Peru" },
    { id: 7, name: "Bali Ubud Rice Terraces", price: "$80", discount: "15%", image: "/images/tour7.jpg", category: "Tours", rating: 4.4, reviews: 22, location: "Bali" },
    { id: 8, name: "Dubai Desert Safari", price: "$200", discount: "30%", image: "/images/tour8.jpg", category: "Tours", rating: 4.7, reviews: 30, location: "Dubai" },
    { id: 9, name: "Petra - The Lost City", price: "$220", discount: "10%", image: "/images/tour9.jpg", category: "Tours", rating: 4.5, reviews: 17, location: "Jordan" },
    { id: 10, name: "Sydney Harbour Bridge Climb", price: "AU$250", discount: "5%", image: "/images/tour12.jpg", category: "Tours", rating: 4.6, reviews: 21, location: "Sydney" },
    { id: 11, name: "Tokyo Cherry Blossom Tour", price: "¥12,000", discount: "20%", image: "/images/tour11.jpg", category: "Tours", rating: 4.7, reviews: 19, location: "Tokyo" },
    { id: 12, name: "New York City Helicopter Tour", price: "$350", discount: "15%", image: "/images/tour10.jpg", category: "Tours", rating: 4.9, reviews: 28, location: "New York" },
    { id: 13, name: "Amazon Rainforest Expedition", price: "$500", discount: "25%", image: "/images/tour13.jpg", category: "Tours", rating: 4.6, reviews: 24, location: "Amazon" },
    { id: 14, name: "Egypt Nile Cruise", price: "$450", discount: "10%", image: "/images/tour14.jpg", category: "Tours", rating: 4.5, reviews: 20, location: "Cairo" },
    { id: 15, name: "Mount Everest Base Camp Trek", price: "$900", discount: "15%", image: "/images/tour15.jpg", category: "Tours", rating: 4.8, reviews: 26, location: "Nepal" },
    { id: 16, name: "Paris Seine River Dinner Cruise", price: "€120", discount: "5%", image: "/images/tour18.jpg", category: "Tours", rating: 4.7, reviews: 18, location: "Paris" },
    { id: 17, name: "South Africa Safari & Wildlife", price: "$750", discount: "20%", image: "/images/tour17.jpg", category: "Tours", rating: 4.9, reviews: 29, location: "Kruger Park" },
    { id: 18, name: "Iceland Ice Cave Tour", price: "$300", discount: "10%", image: "/images/tour20.jpg", category: "Tours", rating: 4.5, reviews: 16, location: "Reykjavik" },
    { id: 19, name: "Cinque Terre Hiking Adventure", price: "€180", discount: "15%", image: "/images/tour19.jpg", category: "Tours", rating: 4.6, reviews: 23, location: "Italy" },
    { id: 20, name: "Great Wall of China Trek", price: "$150", discount: "5%", image: "/images/tour16.jpg", category: "Tours", rating: 4.8, reviews: 30, location: "Beijing" },
];